### ISSUE TITLE
Unable to. build app in iOS

### ISSUE THREAD

**Issue by shrynshjn** [ttlock/react-native-ttlock#5]
Hi, while trying to build the app in iOS, I am getting the following error, the example builds successfully.
I am not accustomed to native iOS development so any help or advice will be appreciated.

/node_modules/react-native-ttlock/ios/Ttlock.m:204:61: Incompatible block pointer types sending 'void (^)(TTLockSwitchState)' to parameter of type 'TTGetLockStatusSuccessBlock' (aka 'void (^)(TTLockSwitchState, TTDoorSensorState)')

I have tried deleting node_modules and Podfiles
and reinstalling them. Still, the error persists. I need it working urgently.
Thank you

**Comment by shrynshjn** [comment]
Do i have to add some flags to the compiler ?

**Comment by snips11** [comment]
I am also having this problem

**Comment by ttlock** [comment]
Open file 'yourProject/node_modules/react-native-ttlock/react-native-ttlock.podspe'
Edit 's.dependency 'TTLock', '~> 3.1.0'' to 's.dependency 'TTLock', '3.1.0''
cd 'yourProject/ios/Pods' remove 'Podfile.lock'
pod install

**Comment by ttlock** [comment]
1. Open file 'yourProject/node_modules/react-native-ttlock/react-native-ttlock.podspe'
2. Edit 's.dependency 'TTLock', '~> 3.1.0'' to 's.dependency 'TTLock', '3.1.0''
3. cd 'yourProject/ios/Pods' remove 'Podfile.lock'
4. pod install
